[package]
name = "rust_hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copy_to_output = "2.1.0"
env = "0.0.0"
glob = "0.3.1"
[build-dependencies]
copy_to_output = "2.1.0"
